# 📊 Screener de Ações — Ibovespa

**Objetivo:** Identificar as 20 melhores ações do Ibovespa (excluindo bancos) que atendam a critérios fundamentalistas rigorosos e estejam com preço de mercado abaixo do preço justo calculado por DCF e Graham.

**Critérios de Screening (Ações):**
| # | Critério | Valor |
|---|----------|-------|
| 1 | P/L | entre 0 e 10 |
| 2 | P/PV | entre 0 e 1,5 |
| 3 | Margem EBIT | positiva |
| 4 | Margem Líquida | > 10% |
| 5 | Dívida Líq./EBIT | < 3 |
| 6 | Dívida Líq./PL | < 2 |
| 7 | ROE | > 10% |
| 8 | Liquidez Corrente | > 1 |
| 9 | Passivos/Ativos | < 1 |
| 10 | Liq. Média Diária | > R$ 100 mil |
| 11 | LPA | > 0 |

**Valuation:**
- DCF (Fluxo de Caixa Descontado) — taxa: Selic 14,25%, crescimento histórico
- Fórmula de Graham (com médias P/L e P/PV do setor)

**Bancos:** Lista separada com critérios adaptados.

In [4]:
# === Setup ===
import sys
import importlib
import warnings
import pandas as pd
import numpy as np

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.width', 200)

# Garantir que o diretório raiz está no path para importar src/
if '.' not in sys.path:
    sys.path.insert(0, '.')

from src import scraper, fundamentals, filters, valuation

# Recarregar módulos durante desenvolvimento
for mod in [scraper, fundamentals, filters, valuation]:
    importlib.reload(mod)

print("✅ Módulos carregados com sucesso")

✅ Módulos carregados com sucesso

## 1. Coleta de Tickers

Scraping de `dadosdemercado.com.br/acoes` para obter a lista completa de ações brasileiras, seguido de classificação em **bancos** e **não-bancos**.

In [5]:
# Obter tickers de ações brasileiras
tickers_df = scraper.get_tickers()
print(f"Total de tickers: {len(tickers_df)}")
tickers_df.head(10)

[scraper] 384 tickers obtidos de dadosdemercado.com.br
Total de tickers: 384

  ticker ticker_sa
0  PETR4  PETR4.SA
1  B3SA3  B3SA3.SA
2  RAIZ4  RAIZ4.SA
3  ITUB4  ITUB4.SA
4  CSAN3  CSAN3.SA
5  ITSA4  ITSA4.SA
6  LREN3  LREN3.SA
7  BBDC3  BBDC3.SA
8  MGLU3  MGLU3.SA
9  COGN3  COGN3.SA

## 2. Coleta de Dados Fundamentalistas

Busca de métricas via `yfinance` para todas as ações. Isso pode levar alguns minutos dependendo do número de tickers.

In [6]:
# Coletar fundamentals para todas as ações
stock_fundamentals = fundamentals.fetch_fundamentals(tickers_df['ticker_sa'].tolist(), delay=0.4)
stock_fundamentals.head()

Coletando fundamentals: 100%|██████████| 384/384 [12:43<00:00,  1.99s/it]

[fundamentals] 384 tickers processados, 381 com dados de preço

,ticker_sa,ticker,nome,setor,industria,preco,pl,pvp,margem_ebit_pct,margem_liquida_pct,dl_ebit,dl_pl,roe_pct,liquidez_corrente,passivos_ativos,liq_media_diaria,lpa,vpa,dy_pct,divida_liquida,ebit,fcf_latest,shares_outstanding
0,PETR4.SA,PETR4,PETROBRAS PN ATZ N2,Energy,Oil & Gas Integrated,49.89,6.11,1.55,30.41,22.13,12.07,4.39,28.18,0.71,0.66,3368945977.20,8.16,32.26,7.91,333417000960.00,27614797780.70,16721236676.89,5446501379.00
1,B3SA3.SA,B3SA3,B3 ON NM,Financial Services,Financial Data & Stock Exchanges,17.05,20.54,4.92,86.09,45.54,0.13,0.06,25.59,1.91,0.64,613211775.00,0.83,3.46,3.52,1114740736.00,8666644000.00,4071357000.00,5010732147.00
2,RAIZ4.SA,RAIZ4,RAIZEN PN N2,Utilities,Utilities - Renewable,0.53,NaN,-3.44,0.22,-9.58,107.48,3.51,-231.28,1.69,0.87,31008270.10,-2.15,-0.15,NaN,61700040704.00,574045000.00,-5241328000.00,1349543297.00
3,ITUB4.SA,ITUB4,ITAUUNIBANCOPN EJ N1,Financial Services,Banks - Regional,41.45,10.34,2.23,NaN,32.28,NaN,2.86,21.01,NaN,0.93,1228924107.50,4.01,18.55,1.32,585442983936.00,NaN,27351000000.00,5403525775.00
4,CSAN3.SA,CSAN3,COSAN ON NM,Energy,Oil & Gas Refining & Marketing,5.09,NaN,3.80,0.65,-24.05,155.49,7.69,-28.96,2.58,0.77,196870612.80,-3.89,1.34,NaN,40807221248.00,262450000.00,4566917000.00,3906847275.00

## 3. Screening — Ações (não-bancos)

Aplicação dos 11 critérios fundamentalistas.

In [7]:
# Aplicar filtros fundamentalistas para ações
# Sanitizar colunas numéricas para evitar comparação str vs int nos filtros
numeric_cols = [
    'preco', 'pl', 'pvp', 'margem_ebit_pct', 'margem_liquida_pct',
    'dl_ebit', 'dl_pl', 'roe_pct', 'liquidez_corrente', 'passivos_ativos',
    'liq_media_diaria', 'lpa', 'vpa', 'dy_pct', 'divida_liquida', 'ebit',
    'fcf_latest', 'shares_outstanding'
]

stock_fundamentals_clean = stock_fundamentals.copy()
for col in numeric_cols:
    if col in stock_fundamentals_clean.columns:
        stock_fundamentals_clean[col] = pd.to_numeric(
            stock_fundamentals_clean[col], errors='coerce'
        )

filtered_stocks = filters.apply_stock_filters(stock_fundamentals_clean)

if len(filtered_stocks) > 0:
    display_cols = ['ticker', 'nome', 'setor', 'preco', 'pl', 'pvp',
                    'margem_ebit_pct', 'margem_liquida_pct', 'dl_ebit', 'dl_pl',
                    'roe_pct', 'liquidez_corrente', 'passivos_ativos', 'lpa']
    display(filtered_stocks[display_cols].style.format({
        'preco': 'R$ {:.2f}', 'pl': '{:.2f}', 'pvp': '{:.2f}',
        'margem_ebit_pct': '{:.1f}%', 'margem_liquida_pct': '{:.1f}%',
        'dl_ebit': '{:.2f}', 'dl_pl': '{:.2f}', 'roe_pct': '{:.1f}%',
        'liquidez_corrente': '{:.2f}', 'passivos_ativos': '{:.2f}', 'lpa': 'R$ {:.2f}',
    }))
else:
    print("⚠️ Nenhuma ação passou em todos os 11 critérios."
          "\nIsso pode ocorrer em mercados sobrevalorizados."
          "\nConsidere relaxar alguns critérios.")

[filters] Ações: 23/384 passaram nos 11 critérios

## 4. Valuation — Preço Justo

Cálculo do preço justo de cada ação filtrada por dois métodos:
1. **DCF (Fluxo de Caixa Descontado)** — Taxa de desconto: Selic 14,25% | Crescimento: histórico (CAGR do FCF)
2. **Fórmula de Graham** — `V = √(P/L_setor × P/PV_setor × LPA × VPA)`

Ações com preço de mercado **abaixo de ambos** os preços justos são consideradas subvalorizadas.

In [9]:
# Calcular valuation (DCF + Graham) para ações filtradas
if len(filtered_stocks) > 0:
    valued_stocks = valuation.apply_valuation(filtered_stocks, stock_fundamentals_clean)

    val_cols = ['ticker', 'nome', 'preco', 'preco_justo_dcf', 'preco_justo_graham',
                'margem_seg_dcf_pct', 'margem_seg_graham_pct', 'undervalued']
    display(valued_stocks[val_cols].style.format({
        'preco': 'R$ {:.2f}',
        'preco_justo_dcf': 'R$ {:.2f}',
        'preco_justo_graham': 'R$ {:.2f}',
        'margem_seg_dcf_pct': '{:.1f}%',
        'margem_seg_graham_pct': '{:.1f}%',
    }))
else:
    valued_stocks = pd.DataFrame()
    print("⚠️ Nenhuma ação para avaliar.")

[valuation] 16/23 ações estão abaixo do preço justo (DCF + Graham)

## 5. 🏆 Top 20 Ações — Ranking Final

Ações subvalorizadas (preço de mercado < preço justo DCF **e** Graham), ordenadas por **margem de segurança média**.

In [10]:
# Filtrar apenas ações subvalorizadas e rankear
if len(valued_stocks) > 0 and valued_stocks['undervalued'].any():
    undervalued = valued_stocks[valued_stocks['undervalued']].copy()

    # Margem de segurança média entre DCF e Graham
    undervalued['margem_seg_media_pct'] = (
        undervalued[['margem_seg_dcf_pct', 'margem_seg_graham_pct']].mean(axis=1)
    )

    # Ordenar por maior margem de segurança e pegar top 20
    top20 = (undervalued
             .sort_values('margem_seg_media_pct', ascending=False)
             .head(20)
             .reset_index(drop=True))

    print(f"🏆 TOP {len(top20)} AÇÕES SUBVALORIZADAS\n")

    result_cols = ['ticker', 'nome', 'setor', 'preco', 'preco_justo_dcf',
                   'preco_justo_graham', 'margem_seg_media_pct', 'pl', 'pvp',
                   'roe_pct', 'margem_liquida_pct', 'dl_ebit']
    display(top20[result_cols].style.format({
        'preco': 'R$ {:.2f}',
        'preco_justo_dcf': 'R$ {:.2f}',
        'preco_justo_graham': 'R$ {:.2f}',
        'margem_seg_media_pct': '{:.1f}%',
        'pl': '{:.2f}',
        'pvp': '{:.2f}',
        'roe_pct': '{:.1f}%',
        'margem_liquida_pct': '{:.1f}%',
        'dl_ebit': '{:.2f}',
    }).set_caption("Top 20 — Ações subvalorizadas por margem de segurança"))
else:
    top20 = pd.DataFrame()
    print("⚠️ Nenhuma ação encontrada abaixo do preço justo (DCF + Graham).")

    if len(valued_stocks) > 0:
        # Mostrar as mais próximas de estarem subvalorizadas
        valued_stocks['margem_seg_media_pct'] = (
            valued_stocks[['margem_seg_dcf_pct', 'margem_seg_graham_pct']].mean(axis=1)
        )
        print("\nAções mais próximas do preço justo:")
        near = valued_stocks.nlargest(10, 'margem_seg_media_pct')
        display(near[['ticker', 'nome', 'preco', 'preco_justo_dcf',
                       'preco_justo_graham', 'margem_seg_media_pct']])

🏆 TOP 16 AÇÕES SUBVALORIZADAS

## 7. Resumo da Análise

In [11]:
# Sumário
print("=" * 70)
print("RESUMO DA ANÁLISE")
print("=" * 70)
print(f"Total de tickers analisados:     {len(tickers_df)}")
print(f"\nAções que passaram nos filtros:   {len(filtered_stocks)}")
if len(valued_stocks) > 0:
    print(f"Ações subvalorizadas:            {valued_stocks['undervalued'].sum()}")
print(f"Top 20 selecionadas:             {len(top20)}")
print("=" * 70)
print(f"\nParâmetros DCF: Selic={valuation.SELIC*100:.2f}%, "
      f"Crescimento terminal={valuation.TERMINAL_GROWTH*100:.1f}%, "
      f"Projeção={valuation.PROJECTION_YEARS} anos")
print("Graham: V = √(P/L_setor × P/PV_setor × LPA × VPA)")

======================================================================
RESUMO DA ANÁLISE
======================================================================
Total de tickers analisados:     384

Ações que passaram nos filtros:   23
Ações subvalorizadas:            16
Top 20 selecionadas:             16
======================================================================

Parâmetros DCF: Selic=14.25%, Crescimento terminal=3.5%, Projeção=5 anos
Graham: V = √(P/L_setor × P/PV_setor × LPA × VPA)